server:
  port: 8080

dummyjson:
  api:
    url: https://dummyjson.com/products

management:
  endpoints:
    web:
      exposure:
        include: health, info # Isso irá incluir os endpoints /health e /info
  endpoint:
    health:
      show-details: always